server:
  port: 9191
spring:
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  application:
    name: PAYMENT-SERVICE
logging:
  file:
    name: /Users/anicet/project/hands-lab-java/archive/microservice.log